version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ~/db:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  server:
    image: node:17
    container_name: server
    command: sh -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    driver: bridge
